language: python

os:
  - linux

python:
  - 2.7

addons:
  apt:
    packages:
      - python-setuptools

install:
  - pip install --upgrade pip

env:
  - TEST_DIR=Session4;  TEST_SCRIPT="python setup.py test"

script: cd $TEST_DIR  &&  $TEST_SCRIPT && cd ..
